<?php

/**
 * @file
 * Contains commerce_ups.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_ups_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_ups module.
    case 'help.page.commerce_ups':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('UPS Shipping Module for Drupal 8') . '</p>';
      return $output;

    default:
  }
}
